@startuml Fuzzyficator

interface Mem_func {
	+float operator () (float value)
}

struct Tria_memf implements Mem_func {
	+float a
	+float m
	+float b
	+int edge
	+Tria_memf(a, m, b, edge = 0)
	+float operator() (float value)
}

struct Trap_memf implements Mem_func {
	+float a
	+float b
	+float c
	+float d
	+int edge
	+Trap_memf(a, b, c, d, edge = 0)
	+float operator() (float value)
}

struct Bell_memf implements Mem_func {
	+float std_dev
	+float mid
	+int edge
	+Bell_memf(std_dev, mid, edge = 0)
	+float operator() (float value)
}

class Fuzzyficator {
	+static Mem_func ANY_memf
	+Fuzzyficator()
	+Fuzzyficator(initializer_list<Mem_func> membership_functions)
	+Fuzzyficator(Fuzzyficator)
	+~Fuzzyficator()
	+size_t size()
	+const iterator begin()
	+const iterator end()
	+int operator() (float value, vector<float> &out)
	+int operator() (float value, float*out)
	-vector<Mem_func> mem_funcs
}

@enduml