idf_component_register(SRCS "wifi_slave.cpp" "wifi_master.cpp" "slaveWifi.cpp" "ACControllerSlave.cpp" "ACControllerTask.cpp" "DataProcessTask.cpp" "CommProtocol.cpp" "Telemetry.cpp" "MamdaniController.cpp" "pid.cpp" "ControllerTask.cpp" "TakagiTsugenoController.cpp" "Fuzzyficator.cpp" "taskClass.cpp" "main.cpp"
                    INCLUDE_DIRS ".")
